development:
  adapter: postgresql
  encoding: utf8
  database: RailsEventRegister
  username: walter
  password: w@lter
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: bibapp_test
  username: hading
  password: my_db_password
  host: localhost