development:
  adapter: postgresql
  encoding: utf8
  database: RailsEventRegister
  username: walter
  password: w@lter
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: RailsEventRegister
  username: walter
  password: w@lter
  host: localhost